package starmap

import (
	"encoding/json"
	"fmt"
)

// Characteristic names one of the seven characteristics that are
// generated by arithmetic, in the order the Book 3 p. 4 Planetary
// Characteristics box lists them.
//
// Starport type is not among them. It is a table lookup and never
// arithmetic, so it can never be the subject of a clamp, and the
// technological index matrix takes it as an argument separate from these
// six of its columns.
type Characteristic int

// The characteristics, in p. 4 order.
const (
	Size Characteristic = iota
	Atmosphere
	Hydrographics
	Population
	Government
	LawLevel
	TechIndex
)

func characteristicNames() [7]string {
	return [...]string{
		Size:          "size",
		Atmosphere:    "atmosphere",
		Hydrographics: "hydrographics",
		Population:    "population",
		Government:    "government",
		LawLevel:      "law_level",
		TechIndex:     "tech_index",
	}
}

// Characteristics lists them in p. 4 order.
func Characteristics() []Characteristic {
	return []Characteristic{Size, Atmosphere, Hydrographics, Population, Government, LawLevel, TechIndex}
}

// Valid reports whether the value names a characteristic.
func (c Characteristic) Valid() bool { return c >= Size && c <= TechIndex }

// String returns the name the record carries.
func (c Characteristic) String() string {
	if !c.Valid() {
		return fmt.Sprintf("Characteristic(%d)", int(c))
	}

	return characteristicNames()[c]
}

// MarshalJSON writes the name the record carries.
func (c Characteristic) MarshalJSON() ([]byte, error) {
	if !c.Valid() {
		return nil, fmt.Errorf("%w: %d", ErrNotACharacteristic, int(c))
	}

	b, err := json.Marshal(characteristicNames()[c])
	if err != nil {
		return nil, fmt.Errorf("marshaling characteristic %s: %w", c, err)
	}

	return b, nil
}

// UnmarshalJSON reads the name the record carries.
func (c *Characteristic) UnmarshalJSON(b []byte) error {
	var text string

	err := json.Unmarshal(b, &text)
	if err != nil {
		return fmt.Errorf("reading a characteristic name: %w", err)
	}

	for i, name := range characteristicNames() {
		if name == text {
			*c = Characteristic(i)

			return nil
		}
	}

	return fmt.Errorf("%w: %q", ErrNotACharacteristic, text)
}
