package starmap

import "errors"

// The rules these errors state are the rules of the held pages, so each
// carries its cite here rather than in the message built at the point of
// failure. Callers wrap with %w and add the value that offended.
var (
	// ErrNotACharacteristic is the p. 4 Planetary Characteristics box, less
	// the starport type it opens with. The box lists eight and generates
	// four of them; the rest are thrown on pp. 8 and 9. So the box is cited
	// for the order it lists, never for a count or for the throwing.
	//
	// The book's own "seven basic planetary characteristics" (p. 2) is a
	// different seven: it counts the starport and stops before the
	// technological index. The message therefore names which seven it
	// means rather than citing a seven to a page that does not print one.
	ErrNotACharacteristic = errors.New(
		"not one of the seven characteristics generated by arithmetic, in the order the " +
			"Book 3 p. 4 box lists them; starport type is a table lookup and is not among them")

	// ErrNotADigit and ErrNoDigitForValue are the notation of Book 1 p. 8
	// extended by Book 3 p. 2 (ERRATA E005).
	ErrNotADigit       = errors.New("not in the alphabet of Book 1 p. 8 and Book 3 p. 2")
	ErrNoDigitForValue = errors.New("no digit writes this value")

	// ErrOffGrid and ErrNotAHex are the sub-sector hex grid of Book 3 p. 3.
	ErrOffGrid = errors.New("outside the grid the record is drawn on")
	ErrNotAHex = errors.New("a hex is four digits")

	// ErrOccurrenceDM is the world occurrence DM of Book 3 p. 1, which the
	// page offers as "+1 or -1 on the whole subsector, or on broad areas
	// within a subsector" -- 0 being the absence of one -- and nothing
	// else. One sentinel because the page states one rule: it bounds the
	// record's own DM and every broad area's alike (ERRATA E012).
	ErrOccurrenceDM = errors.New("occurrence DM is not one of -1, 0 or +1 (Book 3 p. 1)")

	// ErrNotAnArea, ErrAreaCorners and ErrAreasOverlap are the broad areas
	// of Book 3 p. 1, read as ERRATA E012 reads them. The page offers the
	// areas and says nothing about their shape, their corners or what a hex
	// in two of them would get; the reading supplies all three, so these
	// cite the entry as well as the page.
	ErrNotAnArea    = errors.New("a broad area is written DM@FROM-TO, as -1@0101-0410 (Book 3 p. 1, ERRATA E012)")
	ErrAreaCorners  = errors.New("a broad area's corners are not its low hex and its high hex (ERRATA E012)")
	ErrAreasOverlap = errors.New(
		"two broad areas share a hex, and Book 3 p. 1 gives no basis for combining two DMs (ERRATA E012)")

	// ErrNotAGrid is the two grids there are: the p. 3 sub-sector grid,
	// and the sector of sixteen of them (ERRATA E006). The schema states
	// the same pair, and the two must agree -- a schema alone rejects
	// nothing at read time.
	ErrNotAGrid = errors.New("not the p. 3 sub-sector grid nor a sector of sixteen of them")

	// ErrNotAStarport is the starport types of Book 3 p. 4.
	ErrNotAStarport = errors.New("not one of A B C D E X (Book 3 p. 4)")

	// ErrTrailingContent is the record's own shape: one JSON document.
	ErrTrailingContent = errors.New("more than one document in the record read; a record is one JSON document")

	// ErrNotThisSchema, ErrNotThisRuleset and ErrNotThisRNG are the three
	// provenance stamps record.schema.json states as constants. A record
	// carrying any other value was written by something that is not this
	// engine, and rendering it would report a subsector this tool cannot
	// vouch for -- silently, because every field it reads would still parse.
	ErrNotThisSchema  = errors.New("not a record of this schema version")
	ErrNotThisRuleset = errors.New("not a record of the ruleset this tool implements")
	ErrNotThisRNG     = errors.New("not a record of the generator this tool draws from")

	// ErrRouteTooFar is the jump routes table of Book 3 p. 2, which states
	// a target at one through four parsecs and none beyond. It is distinct
	// from ErrFieldMissing because a distance of 5 is present and out of
	// range, not absent, and because the document that accepted one told
	// the referee something false about it: legible walks 1 to MaxJump, so
	// the lane was never drawn, and the route table then said it had been
	// suppressed for joining two worlds already joined by shorter ones.
	ErrRouteTooFar = errors.New(
		"a route is longer than the jump routes table states a target for (Book 3 p. 2)")

	// ErrFieldMissing is the ten fields record.schema.json requires. The
	// schema alone rejects nothing at read time, so the two obligations are
	// the schema and this.
	ErrFieldMissing = errors.New("the record is missing a field the schema requires")

	// ErrNotOneCharacter is the shape the record prints these in.
	ErrNotOneCharacter = errors.New("not a single character")
)
